= Advent of code, 2017
:doctype: book
:toc:

image:https://godoc.org/gitlab.com/jhinrichsen/adventofcode2017?status.svg["godoc", link="https://godoc.org/gitlab.com/jhinrichsen/adventofcode2017"]
image:https://goreportcard.com/badge/gitlab.com/jhinrichsen/adventofcode2017["Go report card", link="https://goreportcard.com/report/gitlab.com/jhinrichsen/adventofcode2017"]
image:https://gitlab.com/jhinrichsen/adventofcode2017/badges/master/pipeline.svg[link="https://gitlab.com/jhinrichsen/adventofcode2017/-/commits/master",title="pipeline status"]
image:https://gitlab.com/jhinrichsen/adventofcode2017/badges/master/coverage.svg[link="https://gitlab.com/jhinrichsen/adventofcode2017/-/commits/master",title="coverage report"]

== Overview

Number of tries for a correct answer:

|===
| Day | Part 1 | Part 2
| 1   |   1    |   1
| 2   |   1    |   1
| 3   |   1    |   3
| 4   |   1    |   1
| 5   |   1    |   1
| 6   |   1    |   1
| 7   |   1    |   1
| 8   |   1    |   1
| 9   |   1    |   1
| 10  |   2    |
| 11  |        |
| 12  |   1    |
| 13  |        |
| 14  |        |
| 15  |        |
| 16  |        |
| 17  |        |
| 18  |        |
| 19  |        |
| 20  |        |
| 21  |        |
| 22  |        |
| 23  |        |
| 24  |        |
| 25  |        |
|===

== Day 1: Inverse Captcha

== Day 2: Corruption Checksum

== Day 3: Spiral Memory

=== Part 2

https://oeis.org/A141481

[source,pari]
----
{
	m=5;
	h=2*m-1;
	A=matrix(h, h);
	print1(A[m, m]=1, ", ");
	T=[[1, 0], [1, -1], [0, -1], [ -1, -1], [ -1, 0], [ -1, 1], [0, 1], [1, 1]];

	for (n=1, (h-2)^2-1,
		g=sqrtint(n);
		r=(g+g%2)\2;
		q=4*r^2;
		d=n-q;
		if (n<=q-2*r,
			j=d+3*r;
			k=r, if(n<=q, j=r; k=-d-r, if(n<=q+2*r, j=r-d; k=-r, j=-r; k=d-3*r)));
		j=j+m;
		k=k+m;
		s=0;
		for (c=1, 8, v=[j, k];
			v+=T[c];
			s=s+A[v[1], v[2]]);

		A[j, k]=s;
		print1(s, ", "))
}
----

I know a thing or two about C but this is just too dense to translate to Go.
The PARI based implementation uses no blocks, but comma operators all over the place and for loops in the arguments of a for loop.
I'll take the easy route and use the [https://oeis.org/A141481/b141481.txt] result table.

== Day 4: High-Entropy Passphrases

== Day 5: A Maze of Twisty Trampolines, All Alike

== Day 6: Memory Reallocation

== Day 7: Recursive Circus

== Day 8: I Heard You Like Registers

== Day 9: Stream Processing

== Day 10: Knot Hash

First try 52530 is too high.
Classical off-by-one in index (0..255 <-> 1..256).

== Day 11: Hex Ed

== Day 12: Digital Plumber

== Day 13: Packet Scanners

== Day 14: Disk Defragmentation

== Day 15: Dueling Generators

== Day 16: Permutation Promenade

== Day 17: Spinlock

== Day 18: Duet

== Day 19: A Series of Tubes

== Day 20: Particle Swarm

== Day 21: Fractal Art

== Day 22: Sporifica Virus

== Day 23: Coprocessor Conflagration

== Day 24: Electromagnetic Moat

== Day 25: The Halting Problem
